---
- name: Direct slack
  direct_slack:
    slack_token: "{{ slack_token }}"
    email: "{{ user_email }}"
    message: "Job {{ awx_job_id }} has started, you can see the output at https://awx.jfleming.dev/#/jobs/playbook/{{ awx_job_id }}/output"
  no_log: yes
  when: user_email is defined and user_email|length != 0
  ignore_errors: yes

- name: Direct slack
  direct_slack:
    slack_token: "{{ slack_token }}"
    email: "{{ awx_user_email }}"
    message: "Job {{ awx_job_id }} has started, you can see the output at https://awx.jfleming.dev/#/jobs/playbook/{{ awx_job_id }}/output"
  no_log: yes
  when: user_email is not defined or user_email|length == 0
  ignore_errors: yes

- name: Install and configure API
  block:
  - name: Install Docker
    apt:
      name: docker.io
      state: latest
      update_cache: yes
    become: yes

  - name: Check status of alertmanager service
    service_facts:
    register: service_state

  - name: Register Rollback Version
    command: sudo docker inspect $(sudo docker ps  | awk '{print $2}' | grep -v ID) | jq .[].RepoTags
    register: rollback_version
    when: service_state.ansible_facts.services["api.service"].state == 'running'

  - name: Pull API Image
    command: docker pull devweek.jfrog.io/dev-week/api:{{ version }}
    become: yes

  - name: Install API Service File
    template:
      src: api.service.j2
      dest: /etc/systemd/system/api.service
    become: yes

  - name: Reload Systemd
    systemd:
      daemon_reload: yes
    become: yes

  - name: Enable API Service
    service:
      name: api
      enabled: yes
    become: yes

  - name: Restart API Service
    service:
      name: api
      state: restarted
    become: yes

  - name: Direct slack
    direct_slack:
      slack_token: "{{ slack_token }}"
      email: "{{ user_email }}"
      message: "Job {{ awx_job_id }} has completed, you can see the output at https://awx.jfleming.dev/#/jobs/playbook/{{ awx_job_id }}/output"
    no_log: yes
    when: user_email is defined and user_email|length != 0
    ignore_errors: yes

  - name: Direct slack
    direct_slack:
      slack_token: "{{ slack_token }}"
      email: "{{ awx_user_email }}"
      message: "Job {{ awx_job_id }} has completed, you can see the output at https://awx.jfleming.dev/#/jobs/playbook/{{ awx_job_id }}/output"
    no_log: yes
    when: user_email is not defined or user_email|length == 0
    ignore_errors: yes


  rescue:
    - name: Direct slack
      direct_slack:
        slack_token: "{{ slack_token }}"
        email: "{{ user_email }}"
        message: "Job {{ awx_job_id }} has failed, you can see the output at https://awx.jfleming.dev/#/jobs/playbook/{{ awx_job_id }}/output"
      no_log: yes
      when: user_email is defined and user_email|length != 0
      ignore_errors: yes